baseURL: http://localhost:1313
languageCode: en-us
title: Vibe
log: true
verbose: true
enableRobotsTXT: false
disableKinds:
  - taxonomy
  - taxonomyTerm
buildDrafts: true
buildExpired: true
buildFuture: true
